path: C:\Users\leeru\OneDrive\Desktop\School stuffs\AAI3001 - Computer Vision and Deep Learning
train: train
val: valid

# Classes
names:
  0: fish
  1: jellyfish
  2: penguin
  3: puffin
  4: shark
  5: starfish
  6: stingray